FROM node:12.6.0-buster-slim as builder
WORKDIR /frontend
COPY package*.json /frontend/
RUN npm install
COPY . /frontend
# ARG API_URL
# ENV REACT_APP_HOST_IP_ADDRESS $API_URL
RUN npm run build
ENTRYPOINT ["tail", "-f", "/dev/null"]

FROM nginx:1.18.0-alpine
COPY --from=builder /frontend/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx-proxy.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
